#!/bin/bash

[[ -n "$DEBUG" ]] && set -x

tmpdir=$(mktemp -d)
trap 'cd /;rm -Rf "$tmpdir"' EXIT

schedule="$(cat /opt/voc/schedule_url)"
if [[ -n "$schedule" ]]
then
    curl -qo "$tmpdir/schedule.json" "$schedule"
    curl_exit=$?

    if [[ $curl_exit -ne 0 ]]
    then
        voc2alert "error" "schedule" "Downloading schedule from $schedule failed: curl exited $curl_exit"
    else
        python -m json.tool >/dev/null <"$tmpdir/schedule.json"
        validate_exit=$?

        if [[ $validate_exit -ne 0 ]]
        then
            voc2alert "error" "schedule" "Downloading schedule from $schedule failed: python -m json.tool exited $validate_exit"
        else
            sha_old="$(sha256sum /opt/voc/schedule.json | cut -d' ' -f1)"
            sha_new="$(sha256sum "$tmpdir/schedule.json" | cut -d' ' -f1)"

            if [[ "$sha_old" != "$sha_new" ]]
            then
                chmod go+r "$tmpdir/schedule.json"
                version="$(jq -r '.schedule.version' < "$tmpdir/schedule.json")"
                mv "$tmpdir/schedule.json" "/opt/voc/schedule.json"
                #voc2alert "info" "schedule" "Downloading schedule from $schedule succeeded, fahrplan version $version"
            fi
        fi
    fi
fi

overlays="$(cat /opt/voc/overlays_url)"
if [[ -n "$overlays" ]]
then
    curl -qo "$tmpdir/overlays.tar.gz" "$overlays"
    curl_exit=$?

    if [[ $curl_exit -ne 0 ]]
    then
        voc2alert "error" "overlays" "Downloading overlays from $overlays failed: curl exited $curl_exit"
    else
        sha_old="$(cat /opt/voc/overlays_sha256 2>/dev/null)"
        sha_new="$(sha256sum "$tmpdir/overlays.tar.gz" | cut -d' ' -f1)"

        if [[ "$sha_old" != "$sha_new" ]]
        then
            mkdir "$tmpdir/overlays"
            tar -xzf "$tmpdir/overlays.tar.gz" -C "$tmpdir/overlays"
            tar_exit=$?

            if [[ $tar_exit -ne 0 ]]
            then
                voc2alert "error" "overlays" "Downloading overlays from $overlays failed: tar exited $tar_exit"
            else
                chmod go+r "$tmpdir"/overlays/*.png
                rm -Rf "/opt/voc/overlays"
                mv "$tmpdir/overlays" "/opt/voc/overlays"
                echo "$sha_new" > /opt/voc/overlays_sha256
                voc2alert "info" "overlays" "Downloading overlays from $overlays succeeded"
            fi
        fi
    fi
fi
