name: nix-flake-auto-update
on:
  schedule:
    - cron: "23 3 * * *"
  push:
    paths:
      - '.forgejo/workflows/nix-flake-auto-update.*'

concurrency:
  group: nix-flake-auto-update
  cancel-in-progress: true

jobs:
  nix-flake-auto-update:
    name: "Nix Flake Auto-Update"
    runs-on: nix
    steps:
      - name: Get repo
        run: git clone "https://voc_ci:${{ env.FORGEJO_TOKEN }}@forgejo.c3voc.de/voc/cm.git" "."
      - name: Run updater
        run: .forgejo/workflows/nix-flake-auto-update.sh
