#!/usr/bin/env python3

from os import environ
from os.path import abspath, dirname, expanduser, join

from pykeepass import PyKeePass

from bundlewrap.repo import Repository
from bundlewrap.utils.text import bold, green, red
from bundlewrap.utils.ui import io

KEEPASS_FILE = environ["BW_KEEPASS_FILE"]
KEEPASS_PASSWORD = environ["BW_KEEPASS_PASSWORD"]

SECRETS = {
    "INFLUXDB_URL": {
        "path": ["ansible", "monitoring", "write_htpasswd"],
        "attr": "url",
    },
    "INFLUXDB_USERNAME": {
        "path": ["ansible", "monitoring", "write_htpasswd"],
        "attr": "username",
    },
    "INFLUXDB_PASSWORD": {
        "path": ["ansible", "monitoring", "write_htpasswd"],
        "attr": "password",
    },
}

with io:
    repo = Repository(dirname(dirname(abspath(__file__))))
    with io.job(f"loading keepass repo at {KEEPASS_FILE}"):
        keepass = PyKeePass(expanduser(KEEPASS_FILE), KEEPASS_PASSWORD)

    content = ""

    for secret_name, secret_attrs in sorted(SECRETS.items()):
        with io.job(f"fetching secret {bold(secret_name)}"):
            try:
                result = keepass.find_entries_by_path(secret_attrs["path"], first=True)
                attr = getattr(result, secret_attrs["attr"])
                if not attr:
                    raise AttributeError(secret_attrs["attr"])
                encrypted = repo.vault.encrypt(attr)
            except Exception as e:
                try:
                    encrypted = getattr(repo.libs.keepass, secret_name)
                    if not encrypted:
                        raise AttributeError(secret_name)
                except Exception:
                    io.stderr(
                        f"{bold(secret_name)}  {red('failed')} fetching from {secret_attrs['path']}: {e!r}\n    Could {red('not')} use previous value"
                    )
                    continue
                else:
                    io.stderr(
                        f"{bold(secret_name)}  {red('failed')} fetching from {secret_attrs['path']}: {e!r}\n    Using previous value."
                    )
                    continue

            content += f'''{secret_name} = "{encrypted}"\n'''
            io.stdout(f"{bold(secret_name)}  {green('updated')}")

    with open(join(repo.path, "libs", "keepass.py"), "w") as f:
        f.write(content)

    io.stdout(f"{bold('libs/keepass.py')}  {green('updated')}")
