#!/bin/bash

set -xeuo pipefail

apt-get update

DEBIAN_FRONTEND=noninteractive apt-get -y -q -o Dpkg::Options::=--force-confold dist-upgrade

DEBIAN_FRONTEND=noninteractive apt-get -y -q autoremove

DEBIAN_FRONTEND=noninteractive apt-get -y -q clean
