#!/bin/bash
#set -x

PATH=/usr/bin:/bin
umask 022

MAILTO="ftpmaster"
USERNAME="ftp"
GROUP="uploaders"

BASEDIR="/srv/ftp"
INDEX="${BASEDIR}/INDEX"
TREE="${BASEDIR}/TREE"
NEW="${BASEDIR}/NEW"

cd $BASEDIR
# generate find/INDEX, trim leading ./
sudo -u ftp find -type f 2>/dev/null | sed 's/^..//' | sort > "${INDEX}"

# generate TREE
tree --noreport > "${TREE}"

# generate NEW
echo -e "Files changed in the last 7 days:\n" > "${NEW}"

# filter files generated by this script
#FILTER="(./$(basename ${NEW})\$|./$(basename ${TREE})\$|./$(basename ${INDEX})\$|^\.\$)"
FILTER="(\./INDEX\.gz|\./NEW|\./TREE|\./INDEX|^\.)\$"

sudo -u ftp find -type f -ctime -7 2>/dev/null | egrep -v "${FILTER}" | sort >> "${NEW}"
 
# fix permissions
chown "${USERNAME}:${GROUP}" "${INDEX}" "${TREE}" "${NEW}"
