#!/bin/bash


[[ -n "$DEBUG" ]] && set -x
set -euo pipefail

if [[ -z "$MY_HOSTNAME" ]]
then
    MY_HOSTNAME="$(hostnamectl --static)"
fi

HOSTNAME_SHORT="$(echo "$MY_HOSTNAME" | sed 's/\.c3voc\.de$//g')"
[[ -z "$HOSTNAME_SHORT" ]] && exit 1

MESSAGE="$(jq \
    --null-input \
    --arg level "$1" \
    --arg component "$HOSTNAME_SHORT/$2" \
    --arg msg "$3" \
    --compact-output \
    '{"level": $level, "component": $component, "msg": $msg}')"

for i in 1 2 3 ; do
    voc2mqtt \
        -t '/voc/alert' \
        -m "$MESSAGE" && break
done

for i in 1 2 3 ; do
    voc2mqtt \
        -t "hosts/$MY_HOSTNAME/alert" \
        -m "$MESSAGE" && break
done
