keys:
  - &admin_derchris age1w5lu3zmrs5wqh74447d8zt28dluhgtz6a4cyr6njzpjqyfgjz5usg7d6ms
  - &admin_hexchen age1wvtkhug4q7fcs7wz03kpn77ruqkkwp2xqq30npv4287wtf3w8ukq370vre
  - &admin_jayjay age1yyxdtt7lpcm9hr0y76g559yq4uqz8e8hjc2fzqtwnhctsj99fp6sf3ksl6
  - &admin_ember age1h9tjtrffuewvhkugqc04jja65fv7havvy0xpzdyyykmga8f55drshcq4r4
  - &admin_molly age1rup6s5s63r0tg2qrdtgu5tez9ppj74vccfw2gd2qjrkz66srpq4qj0xyyj
  - &admin_ischluff age19yrsc0ytf42wtmtu23dhd0waylxf890ra6mqmmyz9286t5crj9xqklxk4a
  - &admin_lukas2511 age1l8k6xg79heqf2ptcw84f5479qpwlutd6pzfctsa3pxaxarp52a7s928yj5
  - &admin_keepass age13yl99pyktjyssdm487pa5ucm4rxcrdrt4lq8qk2vkvdwyfhcvahqs4e6cw
  - &host_tel age1glkmsh6pex9g5v95vwx78a8xksmnkvsu7ccnhxzu09yvnfnjudls3lfkru
  - &host_mail age1zcj3dt7uc3gc3kyt6l7m86qjzm9vlgq7kcsm9wh9gank6rqff4gqwrtzpa
  - &host_forgejo age12xvt82l7v3pvk2lk2h4eygse490ww90xp246kutzly27k4ll0uzsy9p8j4
  - &host_loudness age18jzfuerpcgw4cz5lrl36upjfke2txf3jm5znelpy44zpd3mye3ksclfwmy
  - &host_mumble age1azpg9rvlnart0vdhae8rmkkwtlu3mlgusngnsmzwk5k203806gus36nkg5
  - &host_netbox age1r49w444ua6f3wkkl4d33rxg98rk34gt9v4gqzsd68usr52c3qd9qka60tq
  - &host_sso age1p5a9k25d24u2p4pq3xr50d9fx5zjethpesv477hsqs3az2q2zvjsc7jl79
  - &host_wink age18whxlrrx3wlqfrnz5mn54sk46snrs6a5xewn9wqgmt23pvekfe6qm0rgpc
  - &host_live_alb age1tvkr0ujxh7w3pl605rj094eg2flsh9s6uuf0mlhrzs67evre2fas3c68z2
  - &host_live_bre age1fx8dyrfu827shfu7kv8a35wdmjqt5txm30rw7sfmetaa0pvq8u0spyqyqt
  - &host_live_ams age1az0xu3ta86n7kwcm9nvk7fjud78lz3wrckhje5qagv7tzwpw4elsvf02rw
  - &host_live_dus age10jujjsx6rj9mja496r9scp38uq8rdszhc07w2t2hryrkkqcfpf9qywzhx9
  - &host_fra1_wob age1pacmetk7sz6juzswjru2tt3tppzzfme2s5gdkmwusv6tvdyq6gmsntz5sc
  - &host_wob1_wob age1uyaqfnhv0urvya8jt8m0y244hrutkvgvq3nzmyj4fmzw6xg8sfkshac6jk
  - &host_ber1_wob age1f0j5uh79sj7jew5vz5l8e9a4afvfu7jhu0kd3zuq9kkhjat6tsxsptqvxx
  - &host_live_nitk age1sz0ytgt4h6g4622mgmltmkwjsgdwnk3rq59rs8xrh3fnvh8yx4vsufu40d
  - &host_live_ber age1vmucvykug7gn5we7qt5pf9qlh2jyv07n5glfmuchyem420dd8d3qvmvumz
  - &host_live_fem age1pnmhvx0rszcnqulspuqyprw6zcg9htqpgykykfh4dhter85fm4dspgxx3d
  - &host_transcoder1_dus age10ztmyetwq9ptvps7gaf4ngvnu2s9gy8rduaxux09q30hz05qaypsn9w0uu
  - &host_transcoder2_dus age1z9p44yg8gsdfrd0dp7skw2f5n4hdggux07ppquurpwmhdh2lug7qeqfkau
  - &host_transcoder3_dus age193n8sxh7g9awlqlw6txupus5p9q4tdvvv7nnmzz47lcvw4l0t58sgtm72n
  - &host_ingest_alb age1390efny9938c55mxdstsyfleu7r5xee0e800cgrg4cjdk0y6ys9qen0692
  - &host_ingest_dus age1qqg757urfh0rs8649t29c8lgl8d2r5h94h2sa28nylsz7ytzvqjs3ggk98
  - &host_daffy_alb age1gtf3cp88rtleptc3xdr2tt02gtg7rld8q32ylr7m3h4j89nv65yqpsh0rd
  - &host_sylvester_alb age1lng3ppzvdjprkvquznxnv5txgdrta7rkngs459ef762pl3t2t99s3v80u8
  - &host_ns_dus age1fpajflutgl6z2m587f8sru64aqtfeyzkhv30ajufhu562jkxfeussrxugp
  - &host_ns_bre age1zgrguwp0sr2cfd2ve0fepx2l9wavr2jedep92duhv9faa0k8xeqs60gdw7
  - &host_ns_alb age19j84n4780svqh8hy9zkdqtanf6f449kue0h3zfreve87t4nlvetq5ncsv6
  - &host_lb_alb age1q937ydvd40sszx8g4f36fnqjv7y5kuskyg3ssl2r7q99ur0lqqqswtgrk6
  - &host_lb2_alb age1n060mae4lg7g3pucy6l273s2c5vpceve2nf63xv0yud6ncqa7fzqlmr0t0
  - &host_lb_bre age1y03kvs7vqje2gm0hwww34v92z3wwx87k2g505zsrut4q6cfh95esqn3yyd
  - &host_lb_wob age1e8uv5xdsmpqt74w5q5llmfu49xfahgqgcnwg8yvcwt3avjrzvpksxl830u
  - &host_media_dus age19nk6kf9raqt4hu03qhqhsg5gt2hfwe7vet49en66d6d0ss7y49rshukdsh

creation_rules:
  - path_regex: hosts/tel/.*
    key_groups:
    - age:
      - *admin_keepass
      - *admin_hexchen
      - *admin_jayjay
      - *admin_derchris
      - *admin_ember
      - *admin_molly
      - *admin_lukas2511
      - *host_tel

  - path_regex: hosts/mail/.*
    key_groups:
    - age:
      - *admin_keepass
      - *admin_hexchen
      - *admin_jayjay
      - *admin_derchris
      - *admin_ember
      - *admin_molly
      - *admin_lukas2511
      - *host_mail

  - path_regex: modules/voc-ingest/secrets.yaml
    key_groups:
    - age:
      - *admin_keepass
      - *admin_hexchen
      - *admin_jayjay
      - *admin_derchris
      - *admin_ember
      - *admin_molly
      - *admin_lukas2511
      - *host_ingest_alb
      - *host_ingest_dus

  - path_regex: hosts/forgejo/secrets.yaml
    key_groups:
    - age:
      - *admin_keepass
      - *admin_hexchen
      - *admin_jayjay
      - *admin_derchris
      - *admin_ember
      - *admin_molly
      - *admin_lukas2511
      - *host_forgejo

  - path_regex: modules/(voc2mqtt|monitoring-client)/.*
    key_groups:
    - age:
      - *admin_keepass
      - *admin_hexchen
      - *admin_jayjay
      - *admin_derchris
      - *admin_ember
      - *admin_molly
      - *admin_ischluff
      - *admin_lukas2511
      - *host_mail
      - *host_tel
      - *host_loudness
      - *host_forgejo
      - *host_mumble
      - *host_netbox
      - *host_sso
      - *host_wink
      - *host_live_alb
      - *host_live_bre
      - *host_live_ams
      - *host_live_dus
      - *host_fra1_wob
      - *host_wob1_wob
      - *host_ber1_wob
      - *host_live_nitk
      - *host_live_ber
      - *host_live_fem
      - *host_transcoder1_dus
      - *host_transcoder2_dus
      - *host_transcoder3_dus
      - *host_ingest_alb
      - *host_ingest_dus
      - *host_daffy_alb
      - *host_sylvester_alb
      - *host_ns_dus
      - *host_ns_bre
      - *host_ns_alb
      - *host_lb_alb
      - *host_lb2_alb
      - *host_lb_bre
      - *host_lb_wob
      - *host_media_dus

  - path_regex: modules/(voc-relay|upload-server|upload-proxy|stream-transcode)/*
    key_groups:
    - age:
      - *admin_keepass
      - *admin_hexchen
      - *admin_jayjay
      - *admin_derchris
      - *admin_ember
      - *admin_molly
      - *admin_ischluff
      - *admin_lukas2511
      - *host_live_alb
      - *host_live_bre
      - *host_live_ams
      - *host_live_dus
      - *host_fra1_wob
      - *host_wob1_wob
      - *host_ber1_wob
      - *host_live_nitk
      - *host_live_ber
      - *host_live_fem
      - *host_transcoder1_dus
      - *host_transcoder2_dus
      - *host_transcoder3_dus
      - *host_ingest_alb
      - *host_ingest_dus
      - *host_daffy_alb
      - *host_sylvester_alb
  
  - path_regex: modules/voc-nebula/*
    key_groups:
    - age:
      - *admin_keepass
      - *admin_hexchen
      - *admin_jayjay
      - *admin_derchris
      - *admin_ember
      - *admin_molly
      - *admin_ischluff
      - *admin_lukas2511
      - *host_live_alb
      - *host_live_bre
      - *host_live_ams
      - *host_live_dus
      - *host_fra1_wob
      - *host_wob1_wob
      - *host_ber1_wob
      - *host_live_nitk
      - *host_live_ber
      - *host_live_fem
      - *host_transcoder1_dus
      - *host_transcoder2_dus
      - *host_transcoder3_dus
      - *host_ingest_alb
      - *host_ingest_dus
      - *host_daffy_alb
      - *host_sylvester_alb
      - *host_lb_alb
      - *host_lb2_alb
      - *host_lb_bre
      - *host_lb_wob

  - path_regex: modules/voc-knot/*
    key_groups:
    - age:
      - *admin_keepass
      - *admin_hexchen
      - *admin_jayjay
      - *admin_derchris
      - *admin_ember
      - *admin_molly
      - *admin_ischluff
      - *admin_lukas2511
      - *host_ns_dus
      - *host_ns_bre
      - *host_ns_alb

  - path_regex: modules/(voc-loadbalancer|streaming-website)/*
    key_groups:
    - age:
      - *admin_keepass
      - *admin_hexchen
      - *admin_jayjay
      - *admin_derchris
      - *admin_ember
      - *admin_molly
      - *admin_ischluff
      - *admin_lukas2511
      - *host_lb_alb
      - *host_lb2_alb
      - *host_lb_bre
      - *host_lb_wob

  - path_regex: hosts/netbox/.*
    key_groups:
    - age:
      - *admin_keepass
      - *admin_hexchen
      - *admin_jayjay
      - *admin_derchris
      - *admin_ember
      - *admin_molly
      - *admin_ischluff
      - *admin_lukas2511
      - *host_netbox
