{
  ber1-wob = { ... }: { deployment.tags = [ "relays" "edge-relays" ]; };
  daffy-alb = { ... }: { deployment.tags = [ "transcoders" ]; };
  forgejo = { ... }: {};
  fra1-wob = { ... }: { deployment.tags = [ "relays" "edge-relays" ]; };
  ingest-alb = { ... }: { deployment.tags = [ "ingest" ]; };
  ingest-dus = { ... }: { deployment.tags = [ "ingest" ]; };
  lb-alb = { ... }: { deployment.tags = [ "loadbalancers" ]; };
  lb-bre = { ... }: { deployment.tags = [ "loadbalancers" ]; };
  lb-wob = { ... }: { deployment.tags = [ "loadbalancers" ]; };
  live-alb = { ... }: { deployment.tags = [ "relays" "edge-relays" ]; };
  live-ams = { ... }: { deployment.tags = [ "relays" "edge-relays" ]; };
  live-ber = { ... }: { deployment.tags = [ "relays" "origin-relays" ]; };
  live-bre = { ... }: { deployment.tags = [ "relays" "edge-relays" ]; };
  live-dus = { ... }: { deployment.tags = [ "relays" "origin-relays" ]; };
  live-fem = { ... }: { deployment.tags = [ "relays" "edge-relays" ]; };
  live-nitk = { ... }: { deployment.tags = [ "relays" "edge-relays" ]; };
  loudness-player = { ... }: {};
  mail = { ... }: {};
  matrix = { ... }: {};
  monitoring = { ... }: { deployment.tags = [ "monitoring" ]; };
  mqtt = { ... }: {};
  mumble = { ... }: {};
  netbox = { ... }: {};
  ns-alb = { ... }: {};
  ns-bre = { ... }: {};
  ns-dus = { ... }: {};
  sso = { ... }: {};
  sylvester-alb = { ... }: { deployment.tags = [ "transcoders" ]; };
  transcoder1-dus = { ... }: { deployment.tags = [ "transcoders" ]; };
  transcoder2-dus = { ... }: { deployment.tags = [ "transcoders" ]; };
  transcoder3-dus = { ... }: { deployment.tags = [ "transcoders" ]; };
  wink = { ... }: {};
  wob1-wob = { ... }: { deployment.tags = [ "relays" "edge-relays" ]; };
}
