#! /bin/sh
#
#   Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#   Modified for Debian by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#   Modified for yate by Radu Spineanu <radu@timisoara.roedu.net>.
#     and Kilian Krause <kk@verfaction.de>
#
#   What a fucking mess!!1!

### BEGIN INIT INFO
# Provides:          yate
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Yet another telephony engine
# Description:       Start YATE in daemon mode
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/yate
NAME=yate
DESC=yate
PIDFILE=/var/run/$NAME.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

# Include yate defaults if available
if [ -f /etc/default/yate ] ; then
  . /etc/default/yate
fi

if [ "$NO_START" = "1" ];then
  echo Yate Daemon not setup for automagic start. Edit /etc/default/yate to change this.
  exit 0
fi
set -e

case "$1" in
  start)
    echo -n "Starting $DESC: "

    #so yate won't load the client modules
    unset DISPLAY
    if [ ! -e $PIDFILE ]; then
      if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE \
        --user $YATE_USER --group $YATE_GROUP \
        --exec $DAEMON -- -p $PIDFILE $DAEMON_OPTS; then
        log_end_msg 0 || true
      else
        log_end_msg 1 || true
      fi
    else
      echo "$DAEMON is already running."
      exit 1
    fi
    ;;
  stop)
    echo -n "Stopping $DESC: "
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
    rm -f $PIDFILE
    echo "$NAME."
  ;;
  status)
    status_of_proc -p /var/run/yate.pid /usr/bin/yate yate && exit 0 || exit $?
    ;;
  reload)
    echo "Reloading $DESC module files."
    start-stop-daemon --stop --signal HUP --quiet --pidfile $PIDFILE --exec $DAEMON
    ;;
  restart|force-reload)
    echo -n "Restarting $DESC: "
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
    sleep 1

    if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE \
      --user $YATE_USER --group $YATE_GROUP \
      --exec $DAEMON -- -p $PIDFILE $DAEMON_OPTS; then
      log_end_msg 0 || true
    else
      log_end_msg 1 || true
    fi
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|status|reload|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
