#!/bin/bash

[[ -n "$DEBUG" ]] && set -x

set -euo pipefail

EVENT="$2"
TARGET="$1"

if ! [ -d "/video/capture/${EVENT}" ]
then
    echo "Target path not found, refusing to create. Did you run \`bw apply\`?"
    exit 1
fi

while sleep 10
do
    rsync -av --bwlimit=100000 --append --inplace -t "${TARGET}::video/capture/${EVENT}" "/video/capture/"
done
