groups = ["debian-bookworm", "case20_encoders"]

[metadata.crs-worker.secrets]
encoding.secret = "!decrypt:encrypt$gAAAAABpyikpMoYkeVYXv74MTF5NfCs6Ag9hZh8oD6PSWf7g86K2XOzBBrH7EuSV33pytfaq6OPHtJg250Dj7PY1tolgNiBuxpATng2jJkSqql8OJSaW6yKDLAb5AxptNLbE7lRggt2p"
encoding.token = "!decrypt:encrypt$gAAAAABpyijfxbEX4sdfC1LaigaVt0VOppAeZVLYe4fkZe6ua8Ur4qJ5Qfcxhet_pU5kzM3RHzieYBul5q3qY5tiSu9QXKjHrb8XF2hPp5lJ9IcHoLe7z56UVWYyYu4y2xeP4azTXPCy"
meta.secret = "!decrypt:encrypt$gAAAAABpyilCqCklsTLPzawYp7k9ZUTOelTuYo3nz6M1q6lpMtXB7mflW8-FyNq2gVtMO2ernoYX3S8yNw8gC3D38GvOZelT0Yij-NbSVkR6hk-qJ4e8Yqh2tkPMjhodJDJbyg_mcKlX"
meta.token = "!decrypt:encrypt$gAAAAABpyilTwd-ZLPpaa2YtOCElh3AING5rUyXI9epJeaIDbFjO087s2XRkB5eyM5pDqhGQQ8TkPe4u0moY73n3jjCqqkIfKXoCF3xboc71ObGxb38IBfey72D-sWeavOHkO3XU-t5K"

[metadata.event]
room_name = "Hs i1"

[metadata.interfaces.eth0]
ips = ["10.73.1.3/16"]
gateway4 = "10.73.0.254"

[metadata.voctocore]
streaming_auth_key = "!decrypt:encrypt$gAAAAABkMHUzBwe5QRDWbQU9ryOt4IwUdTTG-a1hNB3LU1SLLCOHnTu9hN912VbJ5dJ02Ke4utPA1nllcO6YAR3YBF2eud-iAm3nmr4sKPps3ExItoHk6xE="

[metadata.voctocore.sources.cam1]
devicenumber = 3
mode = "1080p25"

[metadata.voctocore.sources.cam2]
devicenumber = 2
mode = "1080p25"

#[metadata.voctocore.sources.cam3]
#devicenumber = 5
#mode = "1080p25"

[metadata.voctocore.sources.slides]
devicenumber = 4
mode = "1080p25"

[metadata.voctocore.audio.original]
streams = "0+1"
input = "cam1"

[[metadata.zfs.pools.video.when_creating.config]]
type = "mirror"
devices = [
  "/dev/disk/by-id/nvme-Samsung_SSD_990_PRO_4TB_S7DPNU0Y304439F",
  "/dev/disk/by-id/nvme-Samsung_SSD_990_PRO_4TB_S7DPNU0Y304449Z",
]
