groups = ["debian-bookworm", "case20_encoders"]

[metadata.crs-worker.secrets]
encoding.secret = "!decrypt:encrypt$gAAAAABpyiqTodmiccHymcmfqKcdjQFV6DP1wIntCK24zjCly_3X-ZT3t27QXVlyPBlynkq2gECNdIZaQ3Cj_vxQ2FI1CEMoX28_P-KytmQ6wr8OvkzGjlmpg9oHIjQCX-SEFEt_BdX3"
encoding.token = "!decrypt:encrypt$gAAAAABpyiqnPSWn8FFFoa_KJXuoQX1JqTWXqnK-XBYmKYMOysN2Woa0FmDcBsZ06z9XizNvWvg4YWrGxo12pT4uYHp8WCHC-IYpb3yegYlYxebQIuQp4s_tkzx68UTfP5iMnUI2EV0c"
meta.secret = "!decrypt:encrypt$gAAAAABpyiq0i7Thqq2qkV-b9v7mJ2we7uCGXWWT3UlrR6yRqHreLT0fwbvEcjeBNnvqrtGGMYTNXvrbx4SRAn_ekOPBgtY9UVbm3xvfoaR0L_gwp5W9wVtobLy7IWyTkbTVl8VXHsP9"
meta.token = "!decrypt:encrypt$gAAAAABpyirAiDBEO88wMTqKz4h--hUVLUIJDDPkAaomxAz9O7Sp1Qse54QQDJ8LS2z6cyI_7ZCihPg13KF9685JVK_VkaNQl3LJ70IGOT1odILos26gEMbcmVbSJgZn8IdpKKN8iSVh"

[metadata.event]
room_name = "Muenzenbergsaal"

[metadata.interfaces.eth0]
ips = ["10.73.5.3/16"]
gateway4 = "10.73.0.254"

[metadata.voctocore]
streaming_auth_key = "!decrypt:encrypt$gAAAAABkNYkgCo1Orl_R7yyMpMUhESSGiBvMRZy6J3DXw7PWsS7XDvmYjJktYpwn-pdO_CnHzoxbB1OpBh-MfdPZnt7WTA7Vh7V55KPjGpnj73uCHn6fpu8="

[metadata.voctocore.sources.cam1]
devicenumber = 5
mode = "1080p25"

#[metadata.voctocore.sources.cam2]
#devicenumber = 4
#mode = "1080p25"

#[metadata.voctocore.sources.cam3]
#devicenumber = 1
#mode = "1080p25"

[metadata.voctocore.sources.slides]
devicenumber = 0
mode = "1080p25"

[metadata.voctocore.audio.original]
streams = "0+1"
input = "cam1"

[[metadata.zfs.pools.video.when_creating.config]]
type = "mirror"
devices = [
    "/dev/disk/by-id/nvme-Samsung_SSD_990_PRO_4TB_S7DPNU0Y304437R",
    "/dev/disk/by-id/nvme-Samsung_SSD_990_PRO_4TB_S7DPNU0Y304459J",
]
