bundles = [
    "encoder-common",
    "samba",
]
groups = [
    "crs-workers",
    "debian-bullseye",
]

[metadata]
hostname = "storage.voc.fslab.de"

# for the occasional repair task, so users can use a dedicated machine
# to render the output files after preparing in kdenlive
[metadata.apt.packages.frei0r-plugins]
[metadata.apt.packages.melt]

# for intro-outro-generator
[metadata.apt.packages.libmagickwand-dev]

[metadata.crs-worker]
autostart_scripts = [
    "recording-scheduler",
    "mount4cut",
    "cut-postprocessor",
    "postencoding",
    "postprocessing",
]

[metadata.crs-worker.secrets.encoding]
token = "!decrypt:encrypt$gAAAAABpyi2TUqs8REuwTWisacSLiNSy66NMSu-y5qGbxTRR_YJxWVXM6k4dmJ2J1jgu-RU5YQVf4kjqvBCTi_8Mr11UtIDL6jT0ozaZRxC_66vSINty19sxzh1HItvP1cdsmVNlf_cz"
secret = "!decrypt:encrypt$gAAAAABpyi197HWnN3rDezaNO1l9IRS7ieBUwa6jkowuB4SLsQVtJt8AVxziqL_RCCYdhBryd0RL9Ks5rbum1V9ooGPvL1WJmoDUqJmUGb40_RtmMoeM0Ckd6CPp_u3ScoXjjzO4ZzRQ"
