groups = ["debian-trixie"]
bundles = ["loudness-rendering", "voctocore-artwork"]

[metadata]
nameservers = ["10.73.254.201"]

[metadata.interfaces.ens18]
ips = ["10.73.254.64/24"]
gateway4 = "10.73.254.201"

[metadata.loudness-rendering]
from_encoders = [
    "encoder1",
    "encoder2",
    "encoder3",
    "encoder4",
]

[metadata.loudness-rendering.streams.revision]
output = "rtmp://ingest2.c3voc.de/relay/s6_loudness"
room = "Revision"
source = "https://cdn.c3voc.de/hls/revision/native_hd.m3u8"

[metadata.loudness-rendering.streams.revisionextras]
output = "rtmp://ingest2.c3voc.de/relay/s5_loudness"
room = "Revision Extras"
source = "https://cdn.c3voc.de/hls/revisionextras/native_hd.m3u8"
