bundles = ["vsftpd"]
groups = ["debian-bookworm", "case20_minions"]

[metadata.crs-worker.secrets.encoding]
token = "!decrypt:encrypt$gAAAAABpyiyJvGddRtaRtle1YcR30RPkJ1jBj2TM-IwE2H-YUmQazulfQPBHilaHvt_ns61uAWGWxR1ywFArlc-UYHjZYVCfMG40qVhtpL9E3I4ZpeZXHbSO3wi_N6rVxRd0iby5XV-O"
secret = "!decrypt:encrypt$gAAAAABpyix5yl8NvrvctnmwnPr4KGRqmWHrcrUihF9ItzY6iHnXRlPvrISeGXsFaJD3hJs1uoW22mWtDadwyVPvG-wtKEw4hSdGxiP4876hPtNQtl2mN4xVGojkKhraLhB07axASPSF"

[metadata.interfaces.br0]
ips = ["10.73.1.7/16"]
gateway4 = "10.73.0.254"

[metadata.vsftpd.users.saal1-sony]

[[metadata.zfs.pools.zroot.when_creating.config]]
type = "mirror"
devices = [
  "/dev/disk/by-id/nvme-CT4000P3PSSD8_2421E8B2584A-part4",
  "/dev/disk/by-id/nvme-CT4000P3PSSD8_2423E8B7C365-part4",
]
