bundles = ["vsftpd"]
groups = ["debian-trixie", "case20_minions"]

[metadata.crs-worker.secrets.encoding]
token = "!decrypt:encrypt$gAAAAABpyi0NTfcjEvSZM9p4-AgcZdpWt98WlyTrQ4-BCtbozHXxV6K-B-dI1eN60qHH2K2nSM_-wpUQYNnNTRlMxK8EUNPCT0CNeOND3NhtOtfbQ74TiGHNg5gmYTm9ajQrfdfD0M0P"
secret = "!decrypt:encrypt$gAAAAABpyi0aN2Z89X4bk2ST3iZyXtSIXM2IwfGulFhqbkkw2EYVpoS7v_8b0w47QlwGHQQUz7IHLowoVdTcYiOTSYQFCJYlufxDexcdkfRCbDzoiytV7sWElxmAyMrjcNwBeN3TVPVY"

[metadata.interfaces.br0]
ips = ["10.73.5.7/16"]
gateway4 = "10.73.0.254"

[metadata.vsftpd.users.saal5-sony]

[[metadata.zfs.pools.zroot.when_creating.config]]
type = "mirror"
devices = [
  "/dev/disk/by-id/nvme-CT4000P3PSSD8_2421E8B2584E_1-part4",
  "/dev/disk/by-id/nvme-CT4000P3PSSD8_2421E8B25853_1-part4",
]
