bundles = ["vsftpd"]
groups = ["debian-bookworm", "case20_minions"]

[metadata.crs-worker.secrets.encoding]
token = "!decrypt:encrypt$gAAAAABpyiy3o1mcWYx8AhjpBBDnFOqPHgLpybqcjtqEwAHAHhDhmjixO2kEUQDWZxG6mJ2uSA-KykfjFZYiBL8mOWpFAxIdRdmEfg6fi0I_T98zI-3X2kzpe7e2vzZC0tO_oIGJYNO5"
secret = "!decrypt:encrypt$gAAAAABpyizEMPAetBN2gWjM6hctPvMTNrfj118ICoUBL_uxD6EY-ORoGrA9i-Jpeh51Q2e5JpsmTIsWZtKY4DFDMzZbm_pzo5NTdgKuRGDJJ3mtMma7GByKvNYW9G6eZf0EtdbWc1kr"

[metadata.interfaces.br0]
ips = ["10.73.3.7/16"]
gateway4 = "10.73.0.254"

[metadata.vsftpd.users.saal3-sony]

[[metadata.zfs.pools.zroot.when_creating.config]]
type = "mirror"
devices = [
  "/dev/disk/by-id/nvme-CT4000P3PSSD8_2420E8AEBB81_1-part4",
  "/dev/disk/by-id/nvme-CT4000P3PSSD8_2423E8B7C390_1-part4",
]
