#!/usr/bin/env bash

if ! git fetch 2> /dev/null ; then
    echo "Could not fetch latest changes, maybe you are offline?"
    if [ -z "${VOC_ANSIBLE_IGNORE_OFFLINE}" ]; then
        echo "You might break stuff others just fixed..."
        echo "Do you still want to deploy? then type yes"
        read -p "" input
        if [ "x$input" != "xyes" ]; then
            exit 2
        fi
    else
        echo "Whelp, you seem to be in YOLO mode, whatever."
    fi
    echo ""
fi

echo ""
DEPLOY_BRANCH=`git rev-parse --abbrev-ref HEAD`

if [ `git rev-parse --verify origin/$DEPLOY_BRANCH` != `git rev-parse --verify $DEPLOY_BRANCH` ]; then
    echo "You have commits on the $DEPLOY_BRANCH branch not pushed to origin yet. The next operator who deploys ansible will probably break your stuff."
    if [ -z "${VOC_ANSIBLE_IGNORE_UPSTREAM_CHANGES}" ]; then
        echo "do you still want to deploy your unpublished changes? then type yes"
        read -p "" input
        if [ "x$input" != "xyes" ]; then
            exit 2
        fi
    else
        echo "Whelp, you seem to be in YOLO mode, whatever."
    fi
    echo ""
fi

if ! (git diff --exit-code >/dev/null && git diff --cached --exit-code >/dev/null); then
    echo "You have uncomitted changes. The next operator who deploys ansible will probably break your stuff."
    if [ -z "${VOC_ANSIBLE_IGNORE_LOCAL_CHANGES}" ]; then
        echo "do you still which to deploy your unpublished changes? then type yes"
        read -p "" input
        if [ "x$input" != "xyes" ]; then
            exit 2
        fi
    else
        echo "Whelp, you seem to be in YOLO mode, whatever."
    fi
    echo ""
fi


export ANSIBLE_NOCOWS=1

source "_ansible_keepass_util.sh"
set_keepass_dir
ask_keepass_password

#
# Test
#
echo "using keepass file: '${KEEPASS}'"
env KEEPASS="${KEEPASS}" KEEPASS_PW="${KEEPASS_PW}" $(which python) lookup_plugins/keepass.py

#
# Exec
#
exec env KEEPASS="${KEEPASS}" KEEPASS_PW="${KEEPASS_PW}" $(which ansible-playbook) $*
