#!/usr/bin/env bash

source "_ansible_keepass_util.sh"
set_keepass_dir

touch .keepass_version
VERSION_FILE=$(realpath .keepass_version)
KEEPASS_DIR=$(dirname "${KEEPASS}")
(
	cd "$KEEPASS_DIR"
	echo 'Aktualisiere "${VERSION_FILE}" auf: '
	git --no-pager log -1 --pretty=oneline --abbrev-commit
	git rev-parse HEAD > ${VERSION_FILE}
)

