#!/usr/bin/env bash

source "_ansible_keepass_util.sh"

KEEPASS_DIR=$(dirname "${KEEPASS}")
(
	cd "$KEEPASS_DIR"
	echo 'Aktualisiere ".keepass_version" auf: '
	git --no-pager log -1 --pretty=oneline --abbrev-commit
	git rev-parse HEAD > .keepass_version
)

