#!/usr/bin/env bash

source "_ansible_keepass_util.sh"

KEEPASS_DIR=$(dirname "${KEEPASS}")
export GIT_DIR="${KEEPASS_DIR}/.git" 

echo 'Aktualisiere ".keepass_version" auf'
git log -1 --pretty=oneline --abbrev-commit
git rev-parse HEAD > .keepass_version
